apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: devsecops

resources:
  - ../../base

commonLabels:
  environment: prod

# Production: more replicas, more headroom for HPA
patches:
  - target:
      kind: Deployment
      name: devsecops-demo
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
  - target:
      kind: HorizontalPodAutoscaler
      name: devsecops-demo
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 3
      - op: replace
        path: /spec/maxReplicas
        value: 10
