apiVersion: v1
kind: ConfigMap
metadata:
  name: devsecops-demo-config
  namespace: devsecops
  labels:
    app.kubernetes.io/name: devsecops-demo
data:
  APP_NAME: devsecops-demo
  APP_VERSION: "0.1.0"
  FLASK_ENV: production
  LOG_LEVEL: INFO
