apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: devsecops

resources:
  - ../../base

commonLabels:
  environment: dev

# Smaller footprint for the developer cluster
patches:
  - target:
      kind: Deployment
      name: devsecops-demo
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: HorizontalPodAutoscaler
      name: devsecops-demo
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 1
      - op: replace
        path: /spec/maxReplicas
        value: 3
